server:
  port: 8080
  tomcat:
    threads:
      max: 200 # Fallback 

spring:
  application:
    name: role0-core-api
  
  # Java 21 Virtual Threads para alta concorrência O(1)
  threads:
    virtual:
      enabled: true

  # Banco de Dados Geoespacial (Supabase IPv4 / Session Pooler)
  datasource:
    url: jdbc:postgresql://${DB_HOST:aws-1-sa-east-1.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres.dwiufcdrwhbuqrrvlfyb}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # Free tier Supabase maximo é ~15
      minimum-idle: 1
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Hibernate 6 detecta o suporte espacial automaticamente se houver hibernate-spatial
    hibernate:
      ddl-auto: validate
    show-sql: false

  # Cache (Redis)
  data:
    redis:
      host: localhost
      port: 6379

  # Mensageria / EDA (RabbitMQ)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Segurança Customizada
app:
  security:
    jwt:
      secret: "3f8e589A!2e5B876aD*74A4b1c2D3e4F5g6h7i8j9K0" # Apenas ambiente de mock local
      expiration-ms: 86400000 # 24 horas
